import React from 'react';
import { Grid, TextField } from '@material-ui/core';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import ListItemText from '@material-ui/core/ListItemText';
import Avatar from '@material-ui/core/Avatar';

const messageExamples = [
  {
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];

export default function about() {
  return (
    <div style={{ marginTop: '3em' }}>
      <Grid container direction="row">
        <Grid
          item
          container
          direction="column"
          sm
          style={{ marginRight: '1em', marginLeft: '1em' }}
        >

          <div>hello</div>
        </Grid>
        <Grid
          item
          container
          direction="column"
          sm
          style={{ marginRight: '1em', marginLeft: '1em' }}
        >
          <div
            style={{ border: '5px solid pink', width: '45em', height: '40em', overflowY: 'scroll' }}
          >
          {messageExamples.map(({ primary, secondary, person }, index) => (
            <ListItem button key={index + person}>
              <ListItemAvatar>
                <Avatar alt="Profile Picture" src={person} />
              </ListItemAvatar>
              <ListItemText primary={primary} secondary={secondary} />
            </ListItem>
          ))}
          </div>
          <div
            style={{ border: '2px solid pink' , width: '45em', height: '20em' }}
          >
            <List>
      </List>
            <div style={{ margin: '1em' }}>
            <TextField id="outlined-basic" label="Outlined" variant="outlined" />
            </div>
          </div>
        </Grid>
      </Grid>
    </div>
  );
}
